name: hello-udst

on:
  push:
    branches:
      - main

jobs:
  hello-udst-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hello UDST Message
        run: echo "Hello UDST!"
